# Generated by Django 4.0.5 on 2022-08-11 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0011_complains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='prove',
            field=models.ImageField(upload_to='static/proves'),
        ),
    ]
