# Generated by Django 4.0.5 on 2022-08-18 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0013_alter_complains_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='prove',
            field=models.ImageField(blank=True, null=True, upload_to='proves/%y'),
        ),
    ]
