# Generated by Django 4.0.5 on 2022-08-18 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('University', '0015_alter_complains_prove'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complains',
            name='prove',
            field=models.ImageField(upload_to='proves/'),
        ),
    ]
