# Generated by Django 4.0.5 on 2022-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userList',
            fields=[
                ('name', models.CharField(max_length=30, verbose_name='Full name')),
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='User name')),
                ('email', models.CharField(max_length=40, verbose_name='Email')),
                ('phoneNumber', models.CharField(max_length=30, verbose_name='Phone number')),
                ('address', models.CharField(max_length=60, verbose_name='Address')),
            ],
        ),
    ]
